### ISSUE TITLE
No title for the website visible on pages

### ISSUE THREAD

**Issue by briancroxall** [Brown-University-Library/onepress-cds#1]
See [home page](https://worfdev.services.brown.edu/create/cds/). See also a sample [Expertise page](https://worfdev.services.brown.edu/create/cds/expertise/dmp/) or the [About page](https://worfdev.services.brown.edu/create/cds/about/).

**Comment by kerri-hicks** [comment]
The "Center for Digital Scholarship" page title can be added by adding a Hero Image widget to the site. The Widget Title should be "Center for Digital Scholarship." (Or whatever you decide you want it to be.) You can use basic HTML (with square brackets) in the title field.

**Comment by briancroxall** [comment]
I can see the Hero Image widget in the dashboard to the site, and it's been added. But there's still nothing showing up on the pages of the site. Perhaps I'm doing something wrong?

**Comment by briancroxall** [comment]
Looks like it's working now. We might want to make some CSS changes, but that's probably another issue.
