### ISSUE TITLE
Text in search bar for BUL looks odd in Firefox

### ISSUE THREAD

**Issue by briancroxall** [Brown-University-Library/onepress-cds#10]
I've tested this in FF, Chrome, and Safari. It seems fine in everything but FF.

![center for digital scholarship brown university library](https://cloud.githubusercontent.com/assets/1005115/22835225/04ad106c-ef86-11e6-9898-1f8fc7a67e9d.jpg)

**Comment by kerri-hicks** [comment]
It looks good now.
