### ISSUE TITLE
Post template problems

### ISSUE THREAD

**Issue by briancroxall** [Brown-University-Library/onepress-cds#14]
There are two identified problems with the post template. See [this example](https://worfdev.services.brown.edu/create/cds/brown-library-olio/).

- [ ] Post template puts the header/hero below the content. 
- [ ] Library nav bar looks different from other non-post sections of the site.

**Comment by briancroxall** [comment]
This issue grew out of https://github.com/Brown-University-Library/onepress-cds/issues/4.

**Comment by kerri-hicks** [comment]
Updated single.php (the generic post template) to display the hero above the menu.

**Comment by kerri-hicks** [comment]
This has been updated on worfdev, as well.
