### ISSUE TITLE
Posts lose site navigation / menus / header

### ISSUE THREAD

**Issue by briancroxall** [Brown-University-Library/onepress-cds#4]
See [this example](https://worfdev.services.brown.edu/create/cds/test-post/).

**Comment by kerri-hicks** [comment]
I haven't created a post template yet. I'd like to get some info before I do. 

1) Will "people" remain pages, and not posts? (I thought each person was going to be a post, with a category, but if we don't need that functionality, pages are probably better)

2) Do you want a "project" post template and then a different kind of post template for some future kind of generic post? Or can they all look the same?

**Comment by briancroxall** [comment]
1. I'm sure we can convert people from pages to posts. I'm not entirely sure what we get from assigning them to categories though. Obviously "people" would be one of the categories, but then we're just back to where we already are. Would we assign expertise(s) to people and then use those to populate the expertise pages? If so, then that could be useful and save us time.

2. I think we want a "project" post template" and a more generic one as there's a good chance we might want to blog again in the future.

**Comment by kerri-hicks** [comment]
1) Yes, if you wanted to, you could tag each person who does GIS with GIS, and then you'd have a way to find out who the people are who do GIS. Conversely, you could tag the GIS expertise post with people's  names, but that seems backwards.

Then, if you make each person a "post", you can reuse information from the post elsewhere in the site. It will take some automation to do that. If you don't think you want to do that (and you just want to add people's information manually), then I'd make them pages. Does this even make sense?

e.g. I could write code that pulls information out of Andy Creamer's people post, and have that included on his expertise pages. This feature would take significant time to build, so you might have to live with a manual solution for now. But if you think you will ever want the automated solution, you should make the people posts, not pages.

2) OK, I will create a project post template and a generic post template. If you decide you want to automate use of post categories, open another issue (preferably with a low priority). :-)

**Comment by briancroxall** [comment]
1. I understand what you're saying. My first-pass thought about this is that the amount of material we will have on the site is small enough that doing it manually might just be easier than having to spend "significant time" to build the feature that would re-use information. I understand that the re-usability of information is one of the things that makes a CMS like WP worth using in the first place, but I don't know that the up-front costs of its development is worth it in this case. 

That said, it doesn't take a lot of time / energy to create things as posts in the first place, so we could do that with an eye toward the possible future, I suppose? And there are plugins like [this](https://wordpress.org/plugins/post-type-switcher/) that allow one to easily switch the current pages to posts. 

@prashleigh @kerri-hicks What do you think?

2. Great.

**Comment by briancroxall** [comment]
What with the update to the theme that @kerri-hicks added last week, it appears that the post template now includes the WP menu and header/hero. See [this as an example](https://worfdev.services.brown.edu/create/cds/brown-library-olio/). 

However, the template seems to put the header/hero below the content. And the Library nav bar looks different from other non-post sections of the site.

@kerri-hicks Is this worth continuing under this issue? Or should I close it and start a new issue?
