### ISSUE TITLE
header appears twice

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/onepress-cds#42]
On main page it's left adjusted and small. On other pages it's above the main header. Should only appear once

**Comment by cbrusch** [comment]
I think the template for the home page is page.php

**Comment by cbrusch** [comment]
The full structure of the home page seems to be:
header.php
page.php
     content-single.php
          project-list-front-page.php -or- default.php
footer.php

**Comment by cbrusch** [comment]
The hero widget is working properly on posts. The template for posts seems to be single.php
